Add PID file management to archive-log script
Added PID file management to the archive-log script.  This is
used by the post-terminate script to monitor the status of
the archive-log processes while post-terminate is waiting to
remove the tmp directory.

Removed the arbitrary 10 minute timeout from the post-terminate
script.  Instead, now post-terminate will wait as long as
there is at least one instance of archive-log running.

Addresses #970.

diff --git a/bin/post-terminate b/bin/post-terminate
--- a/bin/post-terminate
+++ b/bin/post-terminate
@@ -59,24 +59,35 @@ if [ ! -f .startup ]; then
 fi
 
 ( function waitforarchivelog() {
-      [ "$crash" = "1" ] && return 0
+    [ "$crash" = "1" ] && return 0
 
-      ct=0
-      maxloop=60
-      while [ $ct -lt $maxloop ]; do
-          # check if any log files are in the process of being archived
-          if [ -z "$(find . -maxdepth 1 -name '*.*-*.log' -type f -print -quit 2> /dev/null)" ]; then
-              break
-          fi
-          # wait for background archive-log process (started by bro) to finish
-          sleep 10
-          ((ct++))
-      done
+    # Gather list of all archive-log PID files
+    pidfiles=$(find . -maxdepth 1 -name '.archive-log.*.tmp' -type f -print)
 
-      if [ $ct -lt $maxloop ]; then
-          # all logs have been archived, so we can remove tmp
-          rm -rf $tmp
-      fi
+    while [ -n "$pidfiles" ]; do
+        for pfile in $pidfiles ; do
+            # If PID file is empty, then check it again later
+            if [ -s $pfile ]; then
+                # Check if a process with given PID exists
+                ps -p $(cat $pfile) > /dev/null 2>&1
+                if [ $? -ne 0 ]; then
+                    # No such process exists, so remove PID file
+                    rm -f $pfile
+                fi
+            fi
+        done
+
+        sleep 10
+
+        pidfiles=$(find . -maxdepth 1 -name '.archive-log.*.tmp' -type f -print)
+    done
+
+    # Check if any log files remain (this could happen if the archival
+    # failed, or if archive-log terminated before a log was archived)
+    if [ -z "$(find . -maxdepth 1 -name '*.*-*.log' -type f -print)" ]; then
+        rm -rf $tmp
+    fi
+
   }
 
   for i in *.log; do
