Improve several shell scripts
Added more error checks so that errors are better communicated to the user.
Also added more code comments.

diff --git a/bin/run-bro-on-trace b/bin/run-bro-on-trace
--- a/bin/run-bro-on-trace
+++ b/bin/run-bro-on-trace
@@ -2,23 +2,37 @@
 #
 # Run Bro on a trace file.
 #
-# run-bro-on-trace <installed_policies_flag> <dir-to-set-as-cwd> <trace> <other Bro parameters>
+# run-bro-on-trace <use_installed_policies> <cwd> <trace> <bro_args>
+#
+# use_installed_policies:  1 to use local policy files installed by
+#                          "broctl install", or 0 to use the original files
+# cwd:  directory name to run Bro from
+# trace:  pathname of a trace file
+# bro_args:  string containing Bro cmd-line options
 
 . `dirname $0`/broctl-config.sh
 
+if [ $# -lt 4 ]; then
+    echo "run-bro-on-trace: missing cmd-line arguments"
+    exit 1
+fi
+
 use_installed_policies=$1
-shift
-cwd=$1
-shift
-trace=$1
-shift
+cwd=$2
+trace=$3
+shift 3
 
-source ${scriptsdir}/set-bro-path
+source "${scriptsdir}"/set-bro-path
+if [ $? -ne 0 ]; then
+    exit 1
+fi
 
-cd $cwd
+cd "$cwd"
+if [ $? -ne 0 ]; then
+    exit 1
+fi
 
 echo $@ >.cmdline
-touch .testing
 
-${bro} -r $trace "$@"
+"${bro}" -r "$trace" "$@"
 
