Minor cleanup of the build script
Reorganized a few things in the build script.  Renamed a variable for
clarity.  Removed an unused variable.  Removed a redundant mkdir.
Improved an error message.  Now that BROCTL_TEST directory is no
longer hard-coded to be in /tmp, there's not really any reason for
a user to specify their own location.

diff --git a/testing/Scripts/broctl-test-setup b/testing/Scripts/broctl-test-setup
--- a/testing/Scripts/broctl-test-setup
+++ b/testing/Scripts/broctl-test-setup
@@ -72,7 +72,7 @@ function installcfgfile() {
 
 function installbro() {
     if [ -z "${INSTALL}" ]; then
-        echo "Error: INSTALL not defined (should be in btest.cfg)" 1>&2
+        echo "Error: INSTALL not defined (try 'make buildbro')" 1>&2
         exit 1
     fi
 
