Reorganize and simplify the tests
Reorganized and simplified the tests.  The broctl-test-setup script
no longer requires specifying test-specific config files.  Instead,
they are specified in a more flexible way (only the actual files
needed are specified, both the directory and filename are specified,
and they follow a simple naming scheme that makes their purpose
clear).  It's also easier to change where the tests are run (the
BROCTL_TEST env. var. overrides the directory where the test-specific
bro install directories are located).  Setting BROCTL_TEST_DEBUG
to any value prevents test cases from removing their bro install
directory tree, which can be convenient when debugging a failed
test case.

diff --git a/testing/scripts/broctl-test-setup b/testing/scripts/broctl-test-setup
--- a/testing/scripts/broctl-test-setup
+++ b/testing/scripts/broctl-test-setup
@@ -1,31 +1,114 @@
 #! /usr/bin/env bash
 #
 # Broctl test setup script used with the tests in broctl/testing/btest/*.
-# This script should be run at the start of each test to cleanup and
-# install the necessary files for each test.
-# Usage:  broctl-test-setup <broctl.cfg> <networks.cfg> <node.cfg>
+# This script should be sourced at the start of each test case.  This script
+# will install the necessary files (in directory BROCTL_INSTALL_PREFIX) for
+# each test (cleanup happens automatically unless BROCTL_TEST_DEBUG is
+# defined).
 
-if [ -z "${INSTALL}" ]; then
-    echo "Error: INSTALL not defined in btest.cfg" > /dev/stderr
-    exit 1
-fi
 
-tarfile=${INSTALL}.tar
+# installcfgfile <rel.path> [--new]
+#
+# This function can be used to install a test-specific config file.
+# The <rel.path> is the relative pathname of the config file to install
+# and it must follow a naming convention: <dir>/<dest.name>__<text>
+# where <dir> is the directory, <dest.name> is the destination filename, and
+# <text> is some descriptive text for the config file.
+# If "--new" is given, then skip check for existence of destination file.
+function installcfgfile() {
+    if [ -z "$1" ]; then
+        return
+    fi
 
-if [ ! -f "$tarfile" ]; then
-    echo "Error: $tarfile doesn't exist ('make buildbro' to create)" > /dev/stderr
-    exit 1
-fi
+    # Split input into two cmd-line args.
+    origrelpath=`echo $1 | awk '{print $1}'`
+    newfile=`echo $1 | awk '{print $2}'`
+    if [ "$newfile" = "--new" ]; then
+        newfile="yes"
+    else
+        newfile="no"
+    fi
 
-# Create test-specific bro installation
-basedir=`dirname "${INSTALL}"`
-newprefix="$basedir"/test.$$
-mkdir "$newprefix"
-(cd "$newprefix" && tar xf "$tarfile")
+    # Make sure original file exists
+    origpath=$BROCTLCFG/$origrelpath
+    if [ ! -f "$origpath" ]; then
+        echo "Error: file not found: $origpath"
+        exit 1
+    fi
 
-# install test-specific files
-cp "${BROCTLCFG}/$1" "$newprefix/etc/broctl.cfg"
-cp "${BROCTLCFG}/$2" "$newprefix/etc/networks.cfg"
-cp "${BROCTLCFG}/$3" "$newprefix/etc/node.cfg"
+    # Use the double-underscore delimiter to derive the destination filename
+    relpath=$(echo $origrelpath | awk -F'__' '{print $1}')
+    if [ "$origrelpath" = "$relpath" ]; then
+        echo "Error: filename needs '__': $origrelpath"
+        exit 1
+    fi
+    destfile=$(basename "$relpath")
 
-echo $newprefix
+    # Derive the destination directory based on the original directory
+    destdir=$(dirname "$relpath")
+
+    # Make sure destination directory exists
+    if [ ! -d "$BROCTL_INSTALL_PREFIX/$destdir" ]; then
+        echo "Error: directory not found: $BROCTL_INSTALL_PREFIX/$destdir"
+        exit 1
+    fi
+
+    # Finally, build the destination pathname
+    destpath=$BROCTL_INSTALL_PREFIX/$destdir/$destfile
+
+    if [ "$newfile" = "no" ]; then
+        # Make sure destination file exists (usually, we're overwriting an
+        # existing file, so this is a good safety check to catch typos)
+        if [ ! -f "$destpath" ]; then
+            echo "Error: file not found: $destpath"
+            exit 1
+        fi
+    fi
+
+    cp $origpath $destpath
+}
+
+function installbro() {
+    if [ -z "${INSTALL}" ]; then
+        echo "Error: INSTALL not defined (should be in btest.cfg)" 1>&2
+        exit 1
+    fi
+
+    basedir=`dirname "${INSTALL}"`
+    tarfile=$basedir/bro-test-install.tar
+
+    if [ ! -f "$tarfile" ]; then
+        echo "Error: $tarfile doesn't exist ('make buildbro' to create)" 1>&2
+        exit 1
+    fi
+
+    # Cleanup the test directory only if BROCTL_TEST_DEBUG is not set.
+    if [ -z "${BROCTL_TEST_DEBUG}" ]; then
+        trap "cleanup" EXIT
+    fi
+
+    # Create test-specific bro installation
+    newprefix=$basedir/test.$$
+    mkdir "$newprefix"
+    (cd "$newprefix" && tar xf "$tarfile" && sed -i.orig "s#@PREFIX@#$newprefix#" etc/broctl.cfg)
+
+    export BROCTL_INSTALL_PREFIX=$newprefix
+    export PATH=$BROCTL_INSTALL_PREFIX/bin:$PATH
+
+    # If BROCTL_TEST_DEBUG is set, then leave a file in the test directory
+    # to help setup environment for running broctl manually.
+    if [ -n "${BROCTL_TEST_DEBUG}" ]; then
+        how2run=${BROCTL_INSTALL_PREFIX}/how_to_run_broctl
+        echo "# In order to run broctl in this directory, first type '. how_to_run_broctl'" >> $how2run
+        echo "export PATH=$BROCTL_INSTALL_PREFIX/bin:\$PATH" >> $how2run
+        echo "export BROCTL_INSTALL_PREFIX=$BROCTL_INSTALL_PREFIX" >> $how2run
+    fi
+}
+
+function cleanup() {
+    test -n "$BROCTL_INSTALL_PREFIX" && rm -rf "$BROCTL_INSTALL_PREFIX"
+}
+
+
+installbro
+
diff --git a/testing/scripts/build-bro b/testing/scripts/build-bro
--- a/testing/scripts/build-bro
+++ b/testing/scripts/build-bro
@@ -1,43 +1,55 @@
 #! /usr/bin/env bash
 #
-# This script configures and builds bro for running the broctl tests.
 # Usage:  build-bro [cleanup]
+# This script configures and builds Bro, and then creates a tar file (in
+# directory BROCTL_TEST) of the Bro installation so that each broctl test
+# case will have its own fresh install.
+# If the "cleanup" parameter is specified, then just remove the tar file.
 
-BROCTLSRCDIR=`dirname "$0"`/../..
-BROSRCDIR=${BROCTLSRCDIR}/../..
-PATHSCRIPT=${BROSRCDIR}/build/aux/broctl/broctl-path
 
-# Directory pathname where bro will be installed for broctl test purposes.
-# This directory must not already exist (it will be removed by this script!).
-TESTPREFIX=/tmp/broctltest/orig
+# Absolute path of where a tar file of a Bro installation will be created for
+# broctl test purposes (if not specified by user, then just use a hard-coded
+# value).
+test -z "${BROCTL_TEST}" && BROCTL_TEST=/tmp/broctl_test
 
-if [ -e "${TESTPREFIX}" ]; then
-    echo "Error: directory specified by TESTPREFIX already exists"
-    exit 1
-fi
+# The tar file that all broctl test cases will use.
+TARFILE=${BROCTL_TEST}/bro-test-install.tar
 
 if [ "$1" = "cleanup" ]; then
-    # attempt to remove only if the path is a file
-    test -f "${TESTPREFIX}.tar" && rm -f "${TESTPREFIX}.tar"
+    # attempt to remove the tar file only if the path is a regular file
+    test -f "${TARFILE}" && rm -f "${TARFILE}"
 
     # if the path still exists, then something is wrong
-    if [ -f "${TESTPREFIX}.tar" ]; then
-        echo "Error: unable to remove ${TESTPREFIX}.tar"
+    if [ -f "${TARFILE}" ]; then
+        echo "Error: unable to remove ${TARFILE}"
         exit 1
     fi
 
     exit
 fi
 
-# Verify that the bro git repo was cloned (not just the broctl repo)
+BROCTLSRCDIR=`dirname "$0"`/../..
+BROSRCDIR=${BROCTLSRCDIR}/../..
+PATHSCRIPT=${BROSRCDIR}/build/aux/broctl/broctl-path
+
+# Verify that the entire Bro git repo was cloned (not just the broctl repo).
 if [ ! -e "${BROSRCDIR}/configure" ]; then
     echo "Error: configure script not found. Did you remember to clone the bro repo?"
     exit 1
 fi
 
+# Bro will be built and installed in this temporary directory.
+TESTPREFIX=${BROCTL_TEST}/bro.$$
+
+# As a safety check, make sure the temporary directory does not already exist.
+if [ -e "${TESTPREFIX}" ]; then
+    echo "Error: path already exists: ${TESTPREFIX}"
+    exit 1
+fi
+
 RESTOREPREFIX=0
 
-# Get the original bro install prefix (if any)
+# Get the original Bro install prefix (if any).
 if [ -e "${PATHSCRIPT}" ]; then
     ORIGPREFIX=`"${PATHSCRIPT}"`
 
@@ -47,22 +59,26 @@ if [ -e "${PATHSCRIPT}" ]; then
     fi
 fi
 
-# Rebuild bro, using the broctl test install prefix
+# Build and install Bro in a temporary directory.
 (cd "${BROSRCDIR}" && ./configure --prefix="${TESTPREFIX}" && make && make install)
 test $? -ne 0 && exit 1
 
-# Archive the installation so each test case can use its own prefix without
-# needing to rerun ./configure
-(cd "${TESTPREFIX}" && tar cf "${TESTPREFIX}.tar" * && rm -rf "${TESTPREFIX}")
+# Create a tar file of the installation so each test case can use its own
+# install prefix without needing to rerun ./configure (because configure is
+# very slow).
+(cd "${TESTPREFIX}" && sed -i.orig "s#${TESTPREFIX}#@PREFIX@#" etc/broctl.cfg && tar cf "${TARFILE}" * )
+
+# We no longer need the directory where Bro was installed.
+rm -rf "${TESTPREFIX}"
 
 # Copy the newly-built broctl test path script (this step is needed to
 # avoid referring to the original which might get overwritten in the next step,
-# and also in the case where someone manually rebuilds bro, then manually
-# runs btest on broctl tests)
+# and also in the case where someone manually rebuilds Bro, then manually
+# runs btest on some broctl tests)
 mkdir -p "${BROCTLSRCDIR}/build"
 cp "${PATHSCRIPT}" "${BROCTLSRCDIR}/build"
 
-# Restore (if necessary) the original bro install prefix
+# Restore (if necessary) the original Bro install prefix.
 if [ ${RESTOREPREFIX} -eq 1 ]; then
     (cd "${BROSRCDIR}" && ./configure --prefix="${ORIGPREFIX}")
 fi
