Cleanup the broctl test build and setup scripts
Added better code comments and error messages.  Also a bit of
reorganization.

diff --git a/testing/Scripts/broctl-test-setup b/testing/Scripts/broctl-test-setup
--- a/testing/Scripts/broctl-test-setup
+++ b/testing/Scripts/broctl-test-setup
@@ -1,14 +1,31 @@
 #! /usr/bin/env bash
 #
-# Broctl test setup script (source this at the start of each test script).
+# Broctl test setup script.  This script should be sourced in each test
+# script.  This script requires that some env. vars. are correctly defined
+# in btest.cfg.
 #
 # This script installs Bro to a directory that is unique to each test,
-# and provides a function "installcfgfile" that a test script can 
-# optionally use to install files, and a function "replaceprefix" that a
-# test script can use to alter the contents of a test file to set the
-# correct install directory path.  This script also exports an environment
-# variable "BROCTL_INSTALL_PREFIX" that provides a test script with the
-# directory path of the Bro install.
+# and provides a few functions and environment variables that can be used
+# directly by test scripts.
+#
+# This script provides these functions that can be used directly in
+# test scripts:
+#   installcfgfile    Installs files into the test-specific Bro install dir.
+#   replaceprefix     Replaces text "@PREFIX@" in a specified file with the
+#                     test-specific directory path of the Bro install.
+#
+# This script automatically exports some environment variables that are needed
+# by test scripts:
+#   BROCTL_INSTALL_PREFIX - Test-specific directory path of the Bro install.
+#   PATH - Allows test scripts to run the correct copy of "broctl" without
+#          specifying a path.
+#
+# A user can modify the behavior of this script by setting any of the
+# following env. variables:
+#   BROCTL_TEST_DEBUG - If this is set (value doesn't matter), then the
+#                       test-specific Bro install directory will not be removed
+#                       when a test terminates (this is useful for debugging).
+
 
 
 # installcfgfile <rel.path> [--new]
@@ -99,9 +116,13 @@ replaceprefix() {
     set -x
 }
 
+#####
+# The following functions are needed by this script, but are not likely to be
+# needed by any broctl test scripts.
 
-# This function sets the correct install prefix directory in all files where
-# it's needed (this is done immediately after untarring the Bro install).
+
+# Set the correct install prefix directory in all files where it's needed
+# (this is done immediately after untarring the Bro install).
 replaceprefixes() {
     for i in etc/broctl.cfg bin/broctl lib/broctl/BroControl/version.py ; do
         sed "s#@PREFIX@#${BROCTL_INSTALL_PREFIX}#" $i > $i.new && cp $i.new $i && rm $i.new
@@ -111,46 +132,8 @@ replaceprefixes() {
     done
 }
 
-
-# This function creates a test-specific directory, installs Bro to this
-# directory, and exports some env. vars. with the path of this directory.
-# Cleanup happens automatically unless BROCTL_TEST_DEBUG is defined.
-installbro() {
-    if [ -z "${INSTALL}" ]; then
-        echo "Error: INSTALL not defined (check btest.cfg)" 1>&2
-        exit 1
-    fi
-
-    basedir="${INSTALL}"
-    tarfile=$basedir/bro-test-install.tar
-
-    if [ ! -f "$tarfile" ]; then
-        echo "Error: $tarfile doesn't exist ('make buildbro' to create)" 1>&2
-        exit 1
-    fi
-
-    trap "cleanup" EXIT
-
-    # Create test-specific bro installation directory
-    export BROCTL_INSTALL_PREFIX=$basedir/test.$$
-    mkdir "$BROCTL_INSTALL_PREFIX"
-    test $? -ne 0 && exit 1
-
-    # Install bro
-    (cd "$BROCTL_INSTALL_PREFIX" && tar xf "$tarfile" && replaceprefixes)
-    test $? -ne 0 && exit 1
-
-    export PATH=$BROCTL_INSTALL_PREFIX/bin:$PATH
-
-    # If BROCTL_TEST_DEBUG is set, then leave a file in the test directory
-    # to help setup environment for running broctl manually.
-    if [ -n "${BROCTL_TEST_DEBUG}" ]; then
-        how2run=${BROCTL_INSTALL_PREFIX}/how_to_run_broctl
-        echo "# In order to run broctl in this directory, first type '. ./how_to_run_broctl'" >> $how2run
-        echo "export PATH=$BROCTL_INSTALL_PREFIX/bin:\$PATH" >> $how2run
-    fi
-}
-
+# Cleanup when a broctl test script terminates for any reason (this is called
+# automatically).
 cleanup() {
     set +x
     set +e
@@ -160,16 +143,63 @@ cleanup() {
     # this command will fail if "broctl install" was not run).
     broctl stop > /dev/null 2>&1
 
-    # Cleanup the test directory only if BROCTL_TEST_DEBUG is not set.
+    # Cleanup the test-specific Bro install directory only if BROCTL_TEST_DEBUG
+    # is not set.
     if [ -z "${BROCTL_TEST_DEBUG}" ]; then
         test -n "$BROCTL_INSTALL_PREFIX" && rm -rf "$BROCTL_INSTALL_PREFIX"
     fi
 }
 
-installbro
 
-# Output test commands (if a test fails, this might be useful for debugging)
-set -x
+# Create a test-specific directory, install Bro to this directory, and export
+# the env. vars. BROCTL_INSTALL_PREFIX and PATH which are both needed by
+# broctl test scripts.
+main() {
+    # Exit if any command fails (this is useful to debug a failing broctl test
+    # script).
+    set -e
 
-# Halt the test if any command fails
-set -e
+    if [ -z "${INSTALL}" ]; then
+        echo "Error: the INSTALL env. variable is not defined (should be in btest.cfg)" 1>&2
+        exit 1
+    fi
+
+    basedir="${INSTALL}"
+    tarfile=$basedir/bro-test-install.tar
+
+    if [ ! -f "$tarfile" ]; then
+        echo "Error: $tarfile doesn't exist (run the 'Scripts/build-bro' script)" 1>&2
+        exit 1
+    fi
+
+    trap "cleanup" EXIT
+
+    # Export "BROCTL_INSTALL_PREFIX" which is used in test scripts that need
+    # the directory path of the Bro install.
+    export BROCTL_INSTALL_PREFIX=$basedir/test.$$
+
+    # Create test-specific bro installation directory
+    mkdir "$BROCTL_INSTALL_PREFIX"
+
+    # Install bro
+    (cd "$BROCTL_INSTALL_PREFIX" && tar xf "$tarfile" && replaceprefixes)
+
+    # Update PATH to ensure that test scripts are running the correct copy of
+    # broctl.
+    export PATH=$BROCTL_INSTALL_PREFIX/bin:$PATH
+
+    # If the user set the env. var. BROCTL_TEST_DEBUG, then leave a file in
+    # the test directory to help setup the environment for running broctl
+    # manually.
+    if [ -n "${BROCTL_TEST_DEBUG}" ]; then
+        how2run=${BROCTL_INSTALL_PREFIX}/how_to_run_broctl
+        echo "# In order to run broctl in this directory, type '. ./how_to_run_broctl'" >> $how2run
+        echo "export PATH=$BROCTL_INSTALL_PREFIX/bin:\$PATH" >> $how2run
+    fi
+
+    # Output all commands in a broctl test script (if a test fails, this might
+    # be useful for debugging).
+    set -x
+}
+
+main
diff --git a/testing/Scripts/build-bro b/testing/Scripts/build-bro
--- a/testing/Scripts/build-bro
+++ b/testing/Scripts/build-bro
@@ -1,14 +1,24 @@
 #! /usr/bin/env bash
 #
-# Usage:  build-bro [cleanall]
+# This script builds Bro, then creates a tar file of the Bro installation which
+# will be used by each broctl test case to have its own fresh install of Bro.
+# This script must be run before attempting to run any of the broctl tests.
 #
-# This script configures and builds Bro, and then creates a tar file of
-# the Bro installation so that each broctl test case will have its own
-# fresh install.  If Bro fails to build, then define BROCTL_TEST_BUILDARGS to
-# specify additional "configure" options needed to build Bro.
+# Usage:  build-bro [--clean]
 #
-# If the "cleanall" parameter is specified, then this script just removes
+# If the "--clean" parameter is specified, then this script just removes
 # the tar file and the broctl test build directory.
+#
+# A user can modify the behavior of this script by setting any of these
+# env. variables:
+#   BROCTL_TEST_USEBUILD  - If this is set (value doesn't matter), then Bro
+#                           will be built using the default Bro build directory
+#                           instead of building in a new directory (if Bro has
+#                           already been built, then using this option can save
+#                           time).
+#   BROCTL_TEST_BUILDARGS - Specify additional options that will be passed
+#                           to Bro's "configure" script (this option might be
+#                           useful if Bro fails to build).
 
 
 # This function builds Bro using a build directory specifically for broctl
@@ -30,10 +40,12 @@ build_bro() {
     cd ${BUILDPREFIX} && make && make install
 }
 
+# Replace the Bro install prefix directory path with the text "@PREFIX@".  This
+# is needed so that each BroControl test script can use its own install prefix.
 replaceprefix() {
     # First, fix the BROSCRIPTDIR path (this step is needed to avoid any
-    # unintended difference between PREFIX and BROSCRIPTDIR because on FreeBSD
-    # /home is actually a symlink to /usr/home).
+    # unintended difference between BROSCRIPTDIR and INSTALLPREFIX because on
+    # FreeBSD /home is actually a symlink to /usr/home).
     oldpath=`grep '^BROSCRIPTDIR' lib/broctl/BroControl/version.py | awk -F \" '{ print $2 }'`
     newpath=`canonicalpath "$oldpath"`
     if [ "$newpath" != "$oldpath" ]; then
@@ -50,74 +62,103 @@ replaceprefix() {
     done
 }
 
+# Normalize the specified pathname by resolving any symlinks in the path.
 canonicalpath() {
     newpath=`python -c "from __future__ import print_function; import os,sys; print(os.path.realpath(sys.argv[1]))" "$1"`
     test $? -ne 0 && exit 1
     echo $newpath
 }
 
-BROCTLSRCDIR=`dirname "$0"`/../..
-BROSRCDIR=${BROCTLSRCDIR}/../..
-BROCTLBUILDDIR=${BROCTLSRCDIR}/build
+# Remove the tar file and all test-specific Bro installation directories.
+clean() {
+    definevars
 
-# Absolute path of a directory where all of the broctl test files are located.
-BROCTL_TEST=`canonicalpath "${BROCTLBUILDDIR}/testing"`
-test -z "${BROCTL_TEST}" && exit 1
-
-if [ "$1" = "cleanall" ]; then
-    # verify the path is a directory (and exists) before attempting to remove
+    # Verify the path is a directory (and exists) before attempting to
+    # remove.
     test -d "${BROCTL_TEST}" && rm -rf "${BROCTL_TEST}"
 
-    # if the directory still exists, then something is wrong
+    # If the directory still exists, then something is wrong.
     if [ -d "${BROCTL_TEST}" ]; then
         exit 1
     fi
 
     exit 0
+}
+
+
+definevars() {
+    # Path to the top-level BroControl source code directory.
+    BROCTLSRCDIR=`dirname "$0"`/../..
+
+    # Path to the Bro source code directory.
+    BROSRCDIR=${BROCTLSRCDIR}/../..
+
+    # Path to the BroControl "build" directory.
+    BROCTLBUILDDIR=${BROCTLSRCDIR}/build
+
+    # Absolute path of parent directory where Bro will be installed.
+    BROCTL_TEST=`canonicalpath "${BROCTLBUILDDIR}/testing"`
+    test -z "${BROCTL_TEST}" && exit 1
+}
+
+
+# Create a tar file of the Bro installation.  The tar file will be used by
+# each broctl test script to create a test-specific Bro installation.
+create_tar() {
+    definevars
+
+    # Exit if any command fails.
+    set -e
+
+    # Verify that the entire Bro git repo was cloned (not just the broctl repo).
+    if [ ! -e "${BROSRCDIR}/configure" ]; then
+        echo "Error: in order to run the BroControl tests, you must clone the bro repo (not just the broctl repo)" 1>&2
+        exit 1
+    fi
+
+    # The tar file that all broctl test cases will use.
+    TARFILE=${BROCTL_TEST}/bro-test-install.tar
+
+    # Remove the tar file if it exists
+    if [ -e "${TARFILE}" ]; then
+        rm -f "${TARFILE}"
+    fi
+
+    mkdir -p ${BROCTL_TEST}
+    LOG=${BROCTL_TEST}/buildbro.log
+    rm -f "$LOG"
+
+    # Bro will be installed in this temporary directory.
+    INSTALLPREFIX=${BROCTL_TEST}/bro-install
+
+    # Remove the temporary directory if it exists.
+    if [ -e "${INSTALLPREFIX}" ]; then
+        rm -rf "${INSTALLPREFIX}"
+    fi
+
+    # Don't exit if a command fails.
+    set +e
+
+    # Build and install Bro in the temporary directory.
+    echo "Building Bro (log in $LOG) ..."
+    build_bro >>$LOG 2>&1
+    if [ $? -ne 0 ]; then
+        echo "Error: Bro build failed:" 1>&2
+        tail -n 20 $LOG 1>&2
+        exit 1
+    fi
+
+    # Create a tar file of the installation so each test case can start with a
+    # clean installation without needing to rebuild Bro.
+    (cd "${INSTALLPREFIX}" && replaceprefix && tar cf "${TARFILE}" * )
+    if [ $? -ne 0 ]; then
+        rm -rf "${INSTALLPREFIX}"
+        exit 1
+    fi
+}
+
+if [ "$1" = "--clean" ]; then
+    clean
+else
+    create_tar
 fi
-
-# The tar file that all broctl test cases will use.
-TARFILE=${BROCTL_TEST}/bro-test-install.tar
-
-# Remove the tar file if it exists
-if [ -e "${TARFILE}" ]; then
-    rm -f "${TARFILE}"
-    test $? -ne 0 && exit 1
-fi
-
-mkdir -p ${BROCTL_TEST} || exit 1
-LOG=${BROCTL_TEST}/buildbro.log
-rm -f "$LOG"
-
-# Verify that the entire Bro git repo was cloned (not just the broctl repo).
-if [ ! -e "${BROSRCDIR}/configure" ]; then
-    echo "Error: configure script not found. Did you remember to clone the bro repo?"
-    exit 1
-fi
-
-# Bro will be installed in this temporary directory.
-INSTALLPREFIX=${BROCTL_TEST}/bro-install
-
-# Remove the temporary directory if it exists.
-if [ -e "${INSTALLPREFIX}" ]; then
-    rm -rf "${INSTALLPREFIX}"
-    test $? -ne 0 && exit 1
-fi
-
-# Build and install Bro in a temporary directory.
-echo "Building Bro (log in $LOG) ..."
-build_bro >>$LOG 2>&1
-if [ $? -ne 0 ]; then
-    echo "Error: Bro build failed:"
-    tail -n 20 $LOG
-    exit 1
-fi
-
-# Create a tar file of the installation so each test case can use its own
-# install prefix without needing to rebuild Bro.
-(cd "${INSTALLPREFIX}" && replaceprefix && tar cf "${TARFILE}" * )
-if [ $? -ne 0 ]; then
-    rm -rf "${INSTALLPREFIX}"
-    exit 1
-fi
-
