Improve the build and setup scripts for the broctl tests
Added a new Makefile target "rerun" that reruns any failed tests in
order to avoid having to run "btest -r" manually.  Added another
Makefile target "cleanall" that provides an easier way to remove
the broctl test build directory.

There was no way to specify additional flags to "configure" that are
needed to build Bro, without hand-editing the build script.  Fixed by
allowing a user to define BROCTL_TEST_BUILDARGS containing any needed
configure options.

If the "configure" script failed, then there was no way to run the
tests without manually removing the broctl test build directory and
rebuilding.  Fixed by always running the "configure" script instead
of only when the build directory doesn't exist.

Removed the broctl-path script so that the broctl tests can be run
without needing the broctl test build directory.

Running the test suite the first time takes a long time and consumes
hundreds of MBs of disk space before any tests are run (due to building
Bro), which can be a waste of resources if one just wants to quickly
run both the Bro and broctl test suites.  Fixed by allowing a user to
define BROCTL_TEST_USEBUILD which will use the Bro default build
directory (instead of a custom build directory for the broctl tests).

Remove the tar file containing the Bro install before doing the build
in order to avoid any chance of using an old tar file (when the current
build fails).

Remove the temporary bro install directory before doing a build in
order to avoid a previous "make install" failure causing the user to
have to manually remove that directory.

Added a few more error checks to the build script to better report
errors to the user.

diff --git a/testing/Scripts/broctl-test-setup b/testing/Scripts/broctl-test-setup
--- a/testing/Scripts/broctl-test-setup
+++ b/testing/Scripts/broctl-test-setup
@@ -1,10 +1,11 @@
 #! /usr/bin/env bash
 #
-# Broctl test setup script used with the tests in broctl/testing/btest/*.
-# This script should be sourced at the start of each test case.  This script
-# will install the necessary files (in directory BROCTL_INSTALL_PREFIX) for
-# each test (cleanup happens automatically unless BROCTL_TEST_DEBUG is
-# defined).
+# Broctl test setup script.
+# This script should be sourced at the start of each test case.
+# This script installs Bro to a directory that is unique to each test,
+# and provides a function "installcfgfile" that a test script can 
+# optionally use to install files.
+
 
 # installcfgfile <rel.path> [--new]
 #
@@ -70,13 +71,17 @@ function installcfgfile() {
     set -x
 }
 
+
+# This function creates a test-specific directory, installs Bro to this
+# directory, and exports BROCTL_INSTALL_PREFIX with the path of this directory.
+# Cleanup happens automatically unless BROCTL_TEST_DEBUG is defined.
 function installbro() {
     if [ -z "${INSTALL}" ]; then
-        echo "Error: INSTALL not defined (try 'make buildbro')" 1>&2
+        echo "Error: INSTALL not defined (check btest.cfg)" 1>&2
         exit 1
     fi
 
-    basedir=`dirname "${INSTALL}"`
+    basedir="${INSTALL}"
     tarfile=$basedir/bro-test-install.tar
 
     if [ ! -f "$tarfile" ]; then
@@ -89,13 +94,17 @@ function installbro() {
         trap "cleanup" EXIT
     fi
 
-    # Create test-specific bro installation
+    # Create test-specific bro installation directory
     newprefix=$basedir/test.$$
     mkdir "$newprefix"
-    (cd "$newprefix" && tar xf "$tarfile" && sed "s#@PREFIX@#$newprefix#" etc/broctl.cfg > etc/broctl.cfg.new && mv etc/broctl.cfg.new etc/broctl.cfg)
-
+    test $? -ne 0 && exit 1
     export BROCTL_INSTALL_PREFIX=$newprefix
-    export BROMAGIC=$newprefix/share/bro/magic
+
+    # Install bro
+    (cd "$newprefix" && tar xf "$tarfile" && sed "s#@PREFIX@#$newprefix#" etc/broctl.cfg > etc/broctl.cfg.new && mv etc/broctl.cfg.new etc/broctl.cfg)
+    test $? -ne 0 && exit 1
+
+    export BROMAGIC=$BROCTL_INSTALL_PREFIX/share/bro/magic
     export PATH=$BROCTL_INSTALL_PREFIX/bin:$PATH
 
     # If BROCTL_TEST_DEBUG is set, then leave a file in the test directory
diff --git a/testing/Scripts/build-bro b/testing/Scripts/build-bro
--- a/testing/Scripts/build-bro
+++ b/testing/Scripts/build-bro
@@ -1,20 +1,34 @@
 #! /usr/bin/env bash
 #
-# Usage:  build-bro [cleanup]
+# Usage:  build-bro [cleanall]
 #
 # This script configures and builds Bro, and then creates a tar file of
 # the Bro installation so that each broctl test case will have its own
-# fresh install.
+# fresh install.  If Bro fails to build, then define BROCTL_TEST_BUILDARGS to
+# specify additional "configure" options needed to build Bro.
 #
-# If the "cleanup" parameter is specified, then just remove the tar file.
+# If the "cleanall" parameter is specified, then this script just removes
+# the tar file and the broctl test build directory.
 
+
+# This function builds Bro using a build directory specifically for broctl
+# tests (if BROCTL_TEST_USEBUILD is defined, then the default Bro build
+# directory is used instead).
 function build_bro
 {
+    # Choose a build directory
+    if [ -n "${BROCTL_TEST_USEBUILD}" ]; then
+        # Use the default Bro build directory
+        BUILDPREFIX=build
+    else
+        # Use a build directory specifically for broctl tests
+        BUILDPREFIX=${BROCTL_TEST}/bro-build
+    fi
+
     cd "${BROSRCDIR}"
-    test -d ${BUILDPREFIX} || ./configure --builddir=${BUILDPREFIX} --prefix="${INSTALLPREFIX}"
-    cd ${BUILDPREFIX}
-    make
-    make install
+    ./configure --builddir=${BUILDPREFIX} --prefix="${INSTALLPREFIX}" ${BROCTL_TEST_BUILDARGS}
+    test $? -ne 0 && exit 1
+    cd ${BUILDPREFIX} && make && make install
     test $? -ne 0 && exit 1
 }
 
@@ -22,29 +36,34 @@ BROCTLSRCDIR=`dirname "$0"`/../..
 BROSRCDIR=${BROCTLSRCDIR}/../..
 BROCTLBUILDDIR=${BROCTLSRCDIR}/build
 
-# Absolute path of where a tar file of a Bro installation will be created for
-# broctl test purposes.
+# Absolute path of a directory where all of the broctl test files are located.
 BROCTL_TEST=`python -c "import os,sys; print os.path.realpath(sys.argv[1])" ${BROCTLBUILDDIR}/testing`
+test $? -ne 0 && exit 1
+
+if [ "$1" = "cleanall" ]; then
+    # verify the path is a directory (and exists) before attempting to remove
+    test -d "${BROCTL_TEST}" && rm -rf "${BROCTL_TEST}"
+
+    # if the directory still exists, then something is wrong
+    if [ -d "${BROCTL_TEST}" ]; then
+        exit 1
+    fi
+
+    exit 0
+fi
 
 # The tar file that all broctl test cases will use.
 TARFILE=${BROCTL_TEST}/bro-test-install.tar
 
-if [ "$1" = "cleanup" ]; then
-    # attempt to remove the tar file only if the path is a regular file
-    test -f "${TARFILE}" && rm -f "${TARFILE}"
-
-    # if the path still exists, then something is wrong
-    if [ -f "${TARFILE}" ]; then
-        echo "Error: unable to remove ${TARFILE}"
-        exit 1
-    fi
-
-    exit
+# Remove the tar file if it exists
+if [ -e "${TARFILE}" ]; then
+    rm -f "${TARFILE}"
+    test $? -ne 0 && exit 1
 fi
 
 mkdir -p ${BROCTL_TEST} || exit 1
 LOG=${BROCTL_TEST}/build-bro.log
-rm -f $LOG
+rm -f "$LOG"
 
 # Verify that the entire Bro git repo was cloned (not just the broctl repo).
 if [ ! -e "${BROSRCDIR}/configure" ]; then
@@ -54,12 +73,11 @@ fi
 
 # Bro will be installed in this temporary directory.
 INSTALLPREFIX=${BROCTL_TEST}/bro-install
-BUILDPREFIX=${BROCTL_TEST}/bro-build
 
-# As a safety check, make sure the temporary directory does not already exist.
+# Remove the temporary directory if it exists.
 if [ -e "${INSTALLPREFIX}" ]; then
-    echo "Error: path already exists: ${INSTALLPREFIX}"
-    exit 1
+    rm -rf "${INSTALLPREFIX}"
+    test $? -ne 0 && exit 1
 fi
 
 # Build and install Bro in a temporary directory.
@@ -69,7 +87,11 @@ build_bro >>$LOG 2>&1
 # Create a tar file of the installation so each test case can use its own
 # install prefix without needing to rebuild Bro.
 (cd "${INSTALLPREFIX}" && sed "s#${INSTALLPREFIX}#@PREFIX@#" etc/broctl.cfg > etc/broctl.cfg.new && mv etc/broctl.cfg.new etc/broctl.cfg && tar cf "${TARFILE}" * )
+if [ $? -ne 0 ]; then
+    rm -rf "${INSTALLPREFIX}"
+    exit 1
+fi
 
-# We no longer need the directory where Bro was installed.
+# We no longer need the temporary directory where Bro was installed.
 rm -rf "${INSTALLPREFIX}"
 
