Improve the test build script
When Bro fails to build, the test build script now shows an error message
and some context for why the build failed.

diff --git a/testing/Scripts/build-bro b/testing/Scripts/build-bro
--- a/testing/Scripts/build-bro
+++ b/testing/Scripts/build-bro
@@ -26,9 +26,8 @@ build_bro() {
 
     cd "${BROSRCDIR}"
     ./configure --builddir=${BUILDPREFIX} --prefix="${INSTALLPREFIX}" ${BROCTL_TEST_BUILDARGS}
-    test $? -ne 0 && exit 1
+    test $? -ne 0 && return 1
     cd ${BUILDPREFIX} && make && make install
-    test $? -ne 0 && exit 1
 }
 
 replaceprefix() {
@@ -91,6 +90,11 @@ fi
 # Build and install Bro in a temporary directory.
 echo "Building Bro (log in $LOG) ..."
 build_bro >>$LOG 2>&1
+if [ $? -ne 0 ]; then
+    echo "Error: Bro build failed:"
+    tail -n 20 $LOG
+    exit 1
+fi
 
 # Create a tar file of the installation so each test case can use its own
 # install prefix without needing to rebuild Bro.
