Initial install now provided by CMake.
`broctl install --make` and DevMode=1 option removed, thus releasing
Broctl from dependence on distribution source directories.

Also, scripts are now installed once by CMake, and not generated from
templates at `broctl install` time.  Instead they all source a single
file "broctl-config.sh" generated into the scripts directory by
`broctl install`, which sets the values of all the dynamic variables
that would have otherwise been substituted into the templates.

And some files that aren't used directly by the Broctl installaion
have been relocated into the util/ subdirectory in the source tree.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,157 +1,88 @@
-#! /usr/bin/env python
-#
-# $Id: configure 6952 2009-12-05 00:23:47Z robin $
+#!/bin/sh
+# Convenience wrapper for easily viewing/setting options that
+# the project's CMake scripts will recognize
 
-import os
-import os.path
-import sys
-import stat
-import subprocess
+# check for `cmake` command
+type cmake > /dev/null 2>&1 || {
+    echo "\
+This package requires CMake, please install it first, then you may
+use this configure script to access CMake equivalent functionality.\
+" >&2;
+    exit 1;
+}
 
-Prefix = "/usr/local/bro"  # match Bro's default.
-BroDist = os.path.abspath("../..")
-BroCtlSrc = os.path.join(BroDist, "aux/broctl")
-BroBuild = BroDist
-BroCtlBuild = os.path.join(BroDist, "aux/broctl")
-StandAlone = False
+usage="\
+Usage: $0 [OPTION]... [VAR=VALUE]...
 
-def usage():
-    print """
-Usage: ./configure [--prefix=<dir>] [--brodist=<dir>] [--standalone]
+  Build Directory:
+    --builddir=DIR         place build files in directory [build]
 
-     --prefix=<dir>    Base directory for cluster installation [Default: %s]
-     --brodist=<dir>   Base directory of Bro distribution      [Default: %s]
+  Installation Directories:
+    --prefix=PREFIX        installation directory [/usr/local/bro]
 
-     --standalone      Do a non-cluster, one-Bro-only installation
-""" % (Prefix, BroDist)
-    sys.exit(1)
+  Optional Features:
+    --enable-cluster       enable cluster installation/functionality
 
-args = {}
-for arg in sys.argv[1:]:
-    try:
-        m = arg.find("=")
-        if m >= 0: 
-            opt = arg[0:m].strip()
-	    val = arg[m+1:].strip()
-        else:
-            opt = arg.strip()
-            val = None
+  Required Packages in Non-Standard Locations:
+    --with-bro=PATH        path to Bro install root
+"
 
-        if opt == "--prefix" and val:
-            if val != "NONE":
-                Prefix = os.path.abspath(val)
-                
-        elif opt == "--brodist" and val:
-            BroDist = os.path.abspath(val)
-            BroCtlSrc = os.path.join(BroDist, "aux/broctl")
-            
-        elif opt == "--builddir" and val:
-            BroCtlBuild = os.path.abspath(val)
-            BroBuild = os.path.abspath(os.path.join(BroCtlBuild, "../.."))
-                    
-        elif opt == "--standalone":
-            StandAlone = True
-        else:
-            usage()
-
-        args[opt] = val
-
-    except ValueError:
-        usage()
-
-Version = open(os.path.join(BroDist, "aux/broctl/VERSION")).readline().strip()
-
-try:
-    p = subprocess.Popen("svnversion", stdin=subprocess.PIPE, stdout=subprocess.PIPE, close_fds=True)
-    (stdin, stdout) = (p.stdin, p.stdout)
-    stdin.close()
-    svnversion = stdout.readline().split()[0]
-    if svnversion != "exported":
-        Version += " [r%s]" % svnversion
-except:
-    pass
-        
-bin = os.path.join(BroCtlBuild, "bin")        
-if not os.path.exists(bin):
-    os.mkdir(bin)
-        
-# Create Makefile, bin/broctl and bin/make-env by replacing configuration variables.
-for file in ("Makefile", "bin/broctl", "bin/make-wrapper"):
-
-    src = os.path.join(BroDist, "aux/broctl/%s.in" % file)
-    dst = os.path.join(BroCtlBuild, file)
-
-    try:
-        os.unlink(dst)
-    except OSError:
-        pass
-
-    out = open(dst, "w")
-    
-    for line in open(src):
-        line = line.replace("$PREFIX", Prefix)
-        line = line.replace("$BRODIST", BroDist)
-        line = line.replace("$BROBUILD", BroBuild)
-        line = line.replace("$BROCTLBUILD", BroCtlBuild)
-        line = line.replace("$BROCTLSRC", BroCtlSrc)
-        line = line.replace("$STANDALONE", StandAlone and "True" or "False")
-        line = line.replace("$VERSION", Version)
-        print >>out, line, 
-
-    # Copy the mode of the source file but remove write permission 
-    # to prevent accidental modifications.
-    mode = os.stat(src).st_mode
-    os.chmod(dst, mode &~ 0222)
-
-    print "Created %s." % file
-
-# Create config.status.
-status = os.path.join(BroCtlBuild, "config.status")
-out = open(status, "w")
-print >>out, """#! /bin/sh
-# Generated by configure.
-# Run this file to recreate the current configuration.
-echo Recreating configuration.
-echo
-
-if [ -e ./BroControl ]; then
-    configure=./configure
-    args["--brodist"] = "../../"
-else
-    configure=%s/configure
+sourcedir=`dirname $0`
+if [ "$sourcedir" = "." ]; then
+    sourcedir=`pwd`
 fi
 
-$configure %s && exit
-""" % (BroCtlSrc, " ".join(["%s=%s" % (k, v) for (k, v) in args.items()]))
+# Function to append a CMake cache entry definition to the
+# CMakeCacheEntries variable
+#   $1 is the cache entry variable name
+#   $2 is the cache entry variable type
+#   $3 is the cache entry variable value
+append_cache_entry () {
+    CMakeCacheEntries="$CMakeCacheEntries -D $1:$2=$3"
+}
 
-os.chmod(status, 0750)
+# set defaults
+builddir=build
+CMakeCacheEntries=""
+append_cache_entry CMAKE_INSTALL_PREFIX PATH   /usr/local/bro
+append_cache_entry STANDALONE           BOOL   true
 
-# Done.
+# parse arguments
+while [ $# -ne 0 ]; do
+    case "$1" in
+        -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
+        *) optarg= ;;
+    esac
 
-print """
-            Bro Control Configuration Summary
-==========================================================
+    case "$1" in
+        --help|-h)
+            echo "${usage}" 1>&2
+            exit 1
+            ;;
+        --builddir=*)
+            builddir=$optarg
+            ;;
+        --prefix=*)
+            append_cache_entry CMAKE_INSTALL_PREFIX PATH   $optarg
+            ;;
+        --enable-cluster)
+            append_cache_entry STANDALONE           BOOL   false
+            ;;
+        --with-bro=*)
+            append_cache_entry BRO_ROOT_DIR PATH $optarg
+            ;;
+        *)
+            echo "Invalid option '$1'.  Try $0 --help to see available options."
+            exit 1
+            ;;
+    esac
+    shift
+done
 
-   Installation directory:      %s
-   Bro distribution:            %s
-   Bro build directory:         %s
-   Bro Control distribution:    %s
-   Bro Control build directory: %s
-   
-   Standalone installation:     %s
+# Create build directory
+mkdir -p $builddir
 
-""" % (Prefix, BroDist, BroBuild, BroCtlSrc, BroCtlBuild, (StandAlone and "yes" or "no"))
-
-
-
-
-
-
-
-
-
-
-
-
-
-
+echo "Build Directory : $builddir"
+echo "Source Directory: $sourcedir"
+cd $builddir
+cmake $CMakeCacheEntries $sourcedir
