Check for existence of Bro PID in the "start" script
Before sending the Bro PID back to broctl, the "start" script now fails
with an error message if the PID string is empty.

This might help address BIT-1773.

diff --git a/bin/helpers/start b/bin/helpers/start
--- a/bin/helpers/start
+++ b/bin/helpers/start
@@ -70,6 +70,11 @@ done
 
 pid=`cat .pid`
 
+if [ -z "$pid" ]; then
+    echo "start: failed to get PID of Bro" >&2
+    exit 1
+fi
+
 # The "run-bro" script uses a value of -1 to indicate an error occurred.
 if [ "$pid" = "-1" ]; then
     exit 1
